---
title: "체외진단 성능평가 제출 리포트"
output: html_document
date: "2025-06-18"
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo=FALSE)
library(submission.package)
library(epiR)
library(pROC)
library(dplyr)
library(htmlTable)
library(knitr)
library(kableExtra)

```

## 1. 개요

본 리포트는 체외진단 의료기기 성능평가 결과를 수치적, 시각적으로 정리한 제출용
보고서입니다.

## 2. 데이터 요약
```{r}

data("example_data")
actual=example_data$actual
predicted=example_data$predicted
score=example_data$score

total_n=length(actual)
positive_n=sum(actual==1)
prevalence=positive_n/total_n
data_summary=data.frame(
  Total_Sample=total_n,
  Positive_Cases=positive_n,
  Prevalence=round(prevalence,3)
)
kable(data_summary,caption="샘플 요약",booktabs=TRUE)

```

## 3. 성능 지표 계산
```{r}

metrics=calc_performance_metrics(actual,predicted,score)
formatted=format_performance_output(metrics)
report_ready=format_for_reporting(formatted,digits=3)
kable(report_ready,caption="성능평가 지표",booktabs=TRUE) %>% 
  kable_styling(full_width=F,position="center")

# 성능 결과 저장
save_performance_report(report_ready,format="csv")

```

## 4. ROC Curve 시각화
```{r}

roc_obj=pROC::roc(actual,score)
plot(roc_obj,col="blue",lwd=2,main="ROC Curve")

```

## 5. Confusion Matrix
```{r}

tab=table(factor(predicted,levels=c(1,0)),
          factor(actual,levels=c(1,0)))
rownames(tab)=c("Predicted_positive","Predicted_negative")
colnames(tab)=c("Actual_positive","Actual_negative")
kable(tab,caption="Confusion Matrix",booktabs=TRUE) %>% 
  kable_styling(full_width=F,position="center")

```

## 6. 보고서 생성 이력
```{r}

sessionInfo()

```



